### PR TITLE
Fix trace2P and trace2S functions

### PR DESCRIPTION
**Pull request by Haskell-mouse**
1. There should be `(i + j)`. Otherwise, it would not put diagonal elements into the first row. 
2. Why someone tries to convert the sum of the first row to list and check if it is empty?

### CODE REVIEW

**Comment by tmcdonell** [comment]
Uh, yes, this seems strange...

In fact, I think the `backpermute` should return only the diagonal elements directly to be summed, rather than moving them to the first row and extracting that row using `slice`?

**Comment by tmcdonell** [comment]
(example of what I mean: https://github.com/tmcdonell/accelerate-blas/blob/master/src/Data/Array/Accelerate/Numeric/LinearAlgebra.hs#L178)

**Comment by Haskell-mouse** [comment]
> Uh, yes, this seems strange...
> 
> In fact, I think the `backpermute` should return only the diagonal elements directly to be summed, rather than moving them to the first row and extracting that row using `slice`?

Yes, it is definitely would be better IMO

**Comment by Haskell-mouse** [comment]
Updated the PR

**Comment by tmcdonell** [comment]
Thanks!

**Pull request merged**
